# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'example' do
  use_frameworks!

  # Pods for ascend sdk example app
  pod 'PromiseKit', '~> 6.8'
  pod 'DynamicJSON', '~> 2.0.2'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
end
